name: Deploy to Vercel

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"

    - name: Install dependencies with yarn
      run: yarn

    - name: Deploy to Vercel
      uses: xmflsct/action-vercel-deployment@v0.5.3
      with:
        vercelToken: ${{ secrets.VERCEL_API_TOKEN }}
        vercelOrgId: ${{ secrets.THEPINSTEAM_VERCEL_ORG_ID }}
        vercelProjectId: ${{ secrets.VERCEL_PROJECT_ID }}
        githubToken: ${{ secrets.PAT_THEPINSTEAM }}
        deployProduction: true